[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/malinimahal/*"
  to = "https://ad2d0b32-f9d2-4722-997d-88a6adc1c868-00-iiv8by951cd5.picard.replit.dev/malinimahal/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
